modLoader="javafml"
loaderVersion="[47,)"
license="https://unlicense.org"
[[mods]]
  modId="redefinedlight"
  version="1.0"
  displayName="RedefinedLight"
  logoFile="logo.png"
  credits="Kitminty"
  authors="Kitminty"
  description='''RedefinedLight'''
  [[dependencies.redefinedlight]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
  [[dependencies.redefinedlight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"