modLoader="javafml"
loaderVersion="[4,)"
license="https://unlicense.org"
[[mods]]
modId="redefinedlight"
version="${mod_version}"
displayName="RedefinedLight"
logoFile="logo.png"
credits="Kitminty"
authors="Kitminty"
description='''RedefinedLight'''
[[mixins]]
config="RedefinedLight.mixins.json"
[[dependencies.redefinedlight]]
  modId="neoforge"
  mandatory=true
  versionRange="[4,)"
  ordering="NONE"
  side="BOTH"